### ISSUE TITLE
Constant Error Codes: 500 - Internal Server Error with base64 or FileAPI images (10 or more in a chat)

### ISSUE THREAD

**Issue by simmondsty** [googleapis/js-genai#827]
Upload more than 9 images either through the files api or pass it as base64 and you will get a 500. I am using small images and the payload is well under 20mb, this was working fine until 2 days ago.

**Comment by shmishra99** [comment]
HI @simmondsty , 

Could you please provide a minimal reproducible example so I can investigate the behavior? Thank You!!

**Comment by simmondsty** [comment]
Hi Shivam,

Thank you for your response.

This issue was resolved with the api changes made yesterday. Reverting to the v1beta api fixed it temporarily.

Seems to be the image segmenting update that affected things for a period of 48 hours.

Best reagrds,
Ty

**Comment by Akane7101** [comment]
i'n still having the same issue with 2.5 flash
Group Observer Error: ApiError: {"error":{"code":500,"message":"An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting","status":"INTERNAL"}}
    at throwErrorIfNotOK (/home/container/node_modules/@google/genai/dist/node/index.cjs:13404:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/container/node_modules/@google/genai/dist/node/index.cjs:13180:13
    at async Models.generateContent (/home/container/node_modules/@google/genai/dist/node/index.cjs:14448:24)
    at async /home/container/node_modules/@google/genai/dist/node/index.cjs:6277:30
    at async Chat.sendMessage (/home/container/node_modules/@google/genai/dist/node/index.cjs:6293:9)
    at async observeGroupMessage (/home/container/Core.js:15989:26)
    at async plana (/home/container/Core.js:16372:9) {
  status: 500
}

happens randomly tho
but mostly when dealing with media, (audio and images)

**Comment by Akane7101** [comment]
welp looks like making system instructions shorter fixed the issue
